global.exporter = require('../lib/index').default
global.ResultWrapper = require('../lib/index').ResultWrapper
global.Promise = require 'bluebird'
global.assert = require 'power-assert'
global.path = require 'path'
global.fs = require 'fs'
global.Readable = require('stream').Readable
global.sinon = require 'sinon'
global.PDFResult = require '../node_modules/phantom-html2pdf/lib/pdfResult.js'
